import type { Prescription } from "./data";

/* -------------------------------------------------------------------------
   Generates and downloads a clean A4 PDF of a prescription (all medicines,
   tests and advice). Shared by the patient's Prescriptions page and the
   doctor's prescription builder. jsPDF is imported lazily so it only loads when
   a download actually happens. Client-only (uses the browser).
   ---------------------------------------------------------------------- */
export async function downloadPrescriptionPdf(rx: Prescription, patientName?: string) {
  const { jsPDF } = await import("jspdf");
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const pageW = doc.internal.pageSize.getWidth();
  const pageH = doc.internal.pageSize.getHeight();
  const margin = 48;
  const contentW = pageW - margin * 2;
  let y = margin;

  const ensureSpace = (needed: number) => {
    if (y + needed > pageH - 72) {
      doc.addPage();
      y = margin;
    }
  };

  // Header
  doc.setFont("helvetica", "bold").setFontSize(20).setTextColor(0, 112, 209);
  doc.text("Aria Health", margin, y);
  doc.setFont("helvetica", "normal").setFontSize(11).setTextColor(90);
  doc.text("Digital Prescription", pageW - margin, y, { align: "right" });
  y += 12;
  doc.setDrawColor(220).line(margin, y, pageW - margin, y);
  y += 26;

  // Doctor + date
  doc.setFont("helvetica", "bold").setFontSize(13).setTextColor(20);
  doc.text(rx.doctorName || "Doctor", margin, y);
  doc.setFont("helvetica", "normal").setFontSize(10).setTextColor(110);
  if (rx.specialty) doc.text(rx.specialty, margin, y + 14);
  if (rx.date) doc.text(rx.date, pageW - margin, y, { align: "right" });
  y += 42;

  // Patient
  doc.setFont("helvetica", "normal").setFontSize(9).setTextColor(110);
  doc.text("PATIENT", margin, y);
  doc.setFont("helvetica", "bold").setFontSize(12).setTextColor(20);
  doc.text(patientName || "Patient", margin, y + 15);
  y += 38;

  // Diagnosis
  if (rx.diagnosis) {
    doc.setFont("helvetica", "normal").setFontSize(9).setTextColor(110);
    doc.text("DIAGNOSIS", margin, y);
    doc.setFont("helvetica", "bold").setFontSize(12).setTextColor(20);
    doc.text(rx.diagnosis, margin, y + 15);
    y += 38;
  }

  // Rx / medicines
  doc.setFont("helvetica", "bold").setFontSize(14).setTextColor(20);
  doc.text("Rx", margin, y);
  y += 20;
  if (rx.medicines.length === 0) {
    doc.setFont("helvetica", "normal").setFontSize(10).setTextColor(120);
    doc.text("No medicines prescribed.", margin, y);
    y += 20;
  } else {
    rx.medicines.forEach((m, i) => {
      ensureSpace(36);
      doc.setFont("helvetica", "bold").setFontSize(11).setTextColor(20);
      doc.text(`${i + 1}. ${m.name}`, margin, y);
      const detail = [m.dose, m.frequency, m.duration].filter(Boolean).join("   ·   ");
      if (detail) {
        doc.setFont("helvetica", "normal").setFontSize(10).setTextColor(100);
        doc.text(detail, margin + 16, y + 14);
      }
      y += 34;
    });
  }

  // Tests
  if (rx.tests.length) {
    ensureSpace(40);
    y += 6;
    doc.setFont("helvetica", "normal").setFontSize(9).setTextColor(110);
    doc.text("RECOMMENDED TESTS", margin, y);
    const testLines = doc.splitTextToSize(rx.tests.join(", "), contentW) as string[];
    doc.setFontSize(11).setTextColor(20);
    doc.text(testLines, margin, y + 15);
    y += 15 + testLines.length * 14 + 10;
  }

  // Advice
  if (rx.notes) {
    ensureSpace(50);
    doc.setFont("helvetica", "normal").setFontSize(9).setTextColor(110);
    doc.text("DOCTOR'S ADVICE", margin, y);
    const noteLines = doc.splitTextToSize(rx.notes, contentW) as string[];
    doc.setFontSize(10).setTextColor(40);
    doc.text(noteLines, margin, y + 15);
    y += 15 + noteLines.length * 13 + 10;
  }

  // Footer
  doc.setDrawColor(230).line(margin, pageH - 60, pageW - margin, pageH - 60);
  doc.setFont("helvetica", "normal").setFontSize(8).setTextColor(150);
  doc.text("Generated by Aria Health · This is a digital prescription.", margin, pageH - 44);

  doc.save(`prescription-${rx.id}.pdf`);
}
